# modify smc_monitor.cfg 
- name: modify smc_monitor.cfg conf
  lineinfile:
    path: "{{ smc_monitor_cfg_yml }}"
    regexp: "^{{ key }}:"
    line: "{{ key }}: {{ value }}"
    backrefs: yes
  tags: smc_monitor
  notify: restart smcmonitor
  when: key != "temp_k" and key != IPADDR

# modify /etc/ansible/hosts
- name: modify /etc/ansible/hosts
  lineinfile:
    path: "/etc/ansible/hosts"
    regexp: "IPADDR"
    line: "IPADDR={{ IPADDR }}"
    backrefs: yes
  tags: ansible_hosts

