# File Path
mon_server_cfg: /opt/smc/monitor/conf/mon_server.cfg
mon_server_cfg_yml: /etc/ansible/roles/mon_server/vars/mon_server.cfg.yml

CompName: mon_server
CompFlag: 0de1aab3-d49e-4a60-a3d5-7dab8a17e7c7
LocalAddr: '{{ IPADDR }}'

#日志配置
LogMask: 3
#单个日志文件最大限制，单位M
MaxLogFileSize: 10
LogQueueMask: 3

#文件编码
FileEncode: utf-8

#证书配置，证书路径结尾必须带/
SSLPath: /opt/smc/cert/
SSLCaFile: ca.pem
SSLKeyFile: key.pem
SSLPasswd: AgICrvT4QgQFHAQXnwYHCA==

#总线配置
MQServer: '{{ IPADDR }}'
MQPort: 61616

#smc_monitor监听端口
CmdListenPort: 15002

#监控框架类型,0:monitor 1:urm
MonitorType: 0
