# modify config.properties.yml 
- name: modify config.properties.yml conf
  lineinfile:
    path: "{{ config_properties_yml }}"
    regexp: "^{{ key }}:"
    line: "{{ key }}: {{ value }}"
    backrefs: yes
  tags: config_properties
  notify: restart smcem
  when: key != "temp_k" and key != IPADDR

# modify jmq.properties.yml 
- name: modify jmq.properties.yml conf
  lineinfile:
    path: "{{ jmq_properties_yml }}"
    regexp: "^{{ key }}:"
    line: "{{ key }}: {{ value }}"
    backrefs: yes
  tags: jmq_properties
  notify: restart smcem
  when: key != "temp_k" and key != IPADDR

# modify /etc/ansible/hosts
- name: modify /etc/ansible/hosts
  lineinfile:
    path: "/etc/ansible/hosts"
    regexp: "IPADDR"
    line: "IPADDR={{ IPADDR }}"
    backrefs: yes
  tags: ansible_hosts

