# File Path
smc_monitor_cfg: /opt/smc/monitor/conf/smc_monitor.cfg
smc_monitor_cfg_yml: /etc/ansible/roles/smc_monitor/vars/smc_monitor.cfg.yml

CompName: smc_monitor
CompFlag: 6b616bd0-0309-41a1-8df3-218d46111ff6
LocalAddr: '{{ IPADDR }}'

#日志配置
LogMask: 3
#单个日志文件最大限制，单位M
MaxLogFileSize: 10
LogQueueMask: 3

#mon_server配置
ControlServer: '{{ IPADDR }}'
CmdListenPort: 15002

#证书配置，证书路径结尾必须带/
SSLPath: /opt/smc/cert/
SSLCaFile: ca.pem
SSLKeyFile: key.pem
SSLPasswd: AgICrvT4QgQFHAQXnwYHCA==

#数据库所在分区
DBPartition: /opt
DATAPartition: /opt
WebServer:
DISK_LIMIT: 100

#监控框架类型,0:monitor 1:urm
MonitorType: 0

ServerIdentity:
