# modify vul.cfg
- name: modify vul.cnf conf
  lineinfile:
    path: "{{ vul_cfg_yml }}"
    regexp: "^{{ key }}:"
    line: "{{ key }}: {{ value }}"
    backrefs: yes
  ignore_errors: True
  tags: vul
  notify: restart smcscan
  when: key != "temp_k" and key != IPADDR

# modify /etc/ansible/hosts
- name: modify /etc/ansible/hosts
  lineinfile:
    path: "/etc/ansible/hosts"
    regexp: "IPADDR"
    line: "IPADDR={{ IPADDR }}"
    backrefs: yes
  tags: ansible_hosts
  ignore_errors: True

